
create table t_gp_mottu_pais (
    id_pais bigint generated by default as identity,
    nm_pais varchar(100) not null,
    primary key (id_pais)
);

create table t_gp_mottu_estado (
    id_estado bigint generated by default as identity,
    id_pais bigint,
    nm_estado varchar(100) not null,
    primary key (id_estado)
);


create table t_gp_mottu_cidade (
    id_cidade bigint generated by default as identity,
    id_estado bigint,
    nm_cidade varchar(200) not null,
    primary key (id_cidade)
);

create table t_gp_mottu_endereco (
    nr_logradouro integer not null check (nr_logradouro<=99999),
    cep varchar(8) not null unique,
    id_cidade bigint,
    id_endereco bigint generated by default as identity,
    nm_logradouro varchar(200) not null,
    primary key (id_endereco)
);