create table t_gp_mottu_contato (
    status integer not null check (status<=1),
    id_contato bigint generated by default as identity,
    id_telefone bigint not null unique,
    nm_dono varchar(200) not null,
    primary key (id_contato)
);

create table t_gp_mottu_filial (
    id_contato bigint unique,
    id_endereco bigint unique,
    id_filial bigint generated by default as identity,
    cnpj_filial varchar(14) not null unique,
    senha_filial varchar(200) not null,
    primary key (id_filial)
);

create table t_gp_mottu_perfil (
    id_perfil bigint generated by default as identity,
    nm_perfil enum ('ADMINISTRADOR','AUDITOR','COMERCIAL','FINANCEIRO','GERENTE','MOTOBOY','OPERADOR','RH','SUPERVISOR','TI') not null,
    primary key (id_perfil)
);

create table t_gp_mottu_secoes_filial (
    lado1 float(53) not null,
    lado2 float(53) not null,
    lado3 float(53) not null,
    lado4 float(53) not null,
    id_filial bigint,
    id_secao bigint generated by default as identity,
    id_tipo_secao bigint,
    primary key (id_secao)
);

create table t_gp_mottu_usuario (
    id_filial bigint,
    id_perfil bigint,
    id_usuario bigint generated by default as identity,
    nm_email varchar(200) not null unique,
    nm_usuario varchar(200) not null,
    senha varchar(200) not null,
    primary key (id_usuario)
);

create table t_gp_mottu_telefone (
    ddd varchar(3) not null,
    ddi varchar(3) not null,
    id_telefone bigint generated by default as identity,
    numero varchar(10) not null,
    primary key (id_telefone)
);

create table t_gp_mottu_tipo_secao (
    id_tipo_secao bigint generated by default as identity,
    nm_secao varchar(200) not null,
    primary key (id_tipo_secao)
);