create table t_gp_mottu_moto (
    id_moto bigint generated by default as identity,
    id_secao bigint,
    id_tipo_moto bigint,
    identificador varchar(50) not null unique,
    status varchar(50) not null,
    condicoes_manutencao varchar(200) not null,
    primary key (id_moto)
);

create table t_gp_mottu_qrcode (
    id_filial bigint,
    id_moto bigint unique,
    id_qrcode bigint generated by default as identity,
    vl_qrcode varchar(200) not null,
    primary key (id_qrcode)
);

create table t_gp_mottu_tipo_moto (
    id_tipo_moto bigint generated by default as identity,
    nm_tipo varchar(40) not null,
    primary key (id_tipo_moto)
);